target := "rvsc0-unknown-elf"

import "../common.just"

default: test

# Run all sc0 ISA compliance tests
test:
    python3 main.py

# Run a single source file
test-one file:
    python3 main.py {{file}}
