/* This file is automatically generated.  DO NOT EDIT! */
extern ld_emulation_xfer_type ld_elf32lriscv_emulation;
extern ld_emulation_xfer_type ld_elf64lriscv_emulation;
extern ld_emulation_xfer_type ld_elf32briscv_emulation;
extern ld_emulation_xfer_type ld_elf64briscv_emulation;

#define EMULATION_LIST \
  &ld_elf32lriscv_emulation, \
  &ld_elf64lriscv_emulation, \
  &ld_elf32briscv_emulation, \
  &ld_elf64briscv_emulation, \
  0
